[workspace]
members = [
  "crates/common",
  "crates/gs-sim",
  "crates/vs",
  "crates/tools",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
tokio = { version = "1.39", features = ["rt-multi-thread", "macros", "time", "io-util", "net"] }
quinn = "0.11"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
ed25519-dalek = { version = "2", features = ["rand_core"] }
sha2 = "0.10"
rand = "0.8"
clap = { version = "4.5", features = ["derive"] }
hex = "0.4"
futures = "0.3"
rcgen = "0.12"
rustls = "0.23"
