/* fpp.h: Fair-Play Protocol v1 SDK for C/C++ games.
 *
 * GENERATED by cbindgen from crates/fpp-ffi/src/lib.rs. Do not edit; run
 * `FPP_REGEN_HEADER=1 cargo test -p fpp-ffi --test header` after changing the
 * Rust side. Spec: docs/anticheat/04-protocol.md. Plain C99, 32- and 64-bit.
 */

#ifndef FPP_H
#define FPP_H

#include <stddef.h>
#include <stdint.h>

// Longest session key encoding ([`fpp_signer_session_key`]): a P-256 point.
#define FPP_SESSION_KEY_MAX 65

// `FppArInfo.features` bits: a feature the Verifier reported true.
#define FPP_FEATURE_SECURE_BOOT (1 << 0)

#define FPP_FEATURE_MEASURED_BOOT (1 << 1)

#define FPP_FEATURE_HVCI (1 << 2)

#define FPP_FEATURE_VBS (1 << 3)

#define FPP_FEATURE_IOMMU (1 << 4)

#define FPP_FEATURE_RUNTIME_REPORT (1 << 5)

#define FPP_FEATURE_KEY_IN_HW (1 << 6)

#define FPP_FEATURE_STRONG_INTEGRITY (1 << 7)

#define FPP_FEATURE_APP_ATTESTED (1 << 8)

#define FPP_FEATURE_STRONGBOX (1 << 9)

// `fpp_keys_add` roles: the regional key bundle's keys.
#define FPP_KEY_VERIFIER 1

#define FPP_KEY_BROKER 2

#define FPP_KEY_LIVENESS 3

#define FPP_KEY_ENFORCEMENT 4

// `FppSarInfo.server_class` (04 §6.3).
#define FPP_SERVER_COMMUNITY 0

#define FPP_SERVER_PARTNER 1

#define FPP_SERVER_FIRST_PARTY 2

#define FPP_SERVER_FIRST_PARTY_CVM 3

// Largest datagram the SDK produces or accepts (no IP fragmentation).
#define FPP_P2P_MAX_PACKET 1452

// Largest payload for `fpp_p2p_host_send` / `fpp_p2p_joiner_send`.
#define FPP_P2P_MAX_PAYLOAD 1422

// Largest message for `fpp_p2p_*_send_reliable`.
#define FPP_P2P_MAX_MESSAGE 1418

// Largest address blob.
#define FPP_P2P_MAX_ADDRESS 128

// Largest Attestation Result a joiner may attach.
#define FPP_P2P_MAX_ATTESTATION 512

// Largest title-defined hello, either direction.
#define FPP_P2P_MAX_HELLO 256

// Result of every SDK call. Verification failures map one-to-one onto the
// rejection categories of 04-protocol.md §2.1.
typedef enum FppStatus {
  FPP_STATUS_OK = 0,
  // A required pointer was NULL.
  FPP_STATUS_NULL_POINTER = 1,
  // An argument is out of range or breaks an ordering rule.
  FPP_STATUS_INVALID_ARGUMENT = 2,
  // `*out_len` holds the required size.
  FPP_STATUS_BUFFER_TOO_SMALL = 3,
  // Nothing queued (poll functions).
  FPP_STATUS_EMPTY = 4,
  FPP_STATUS_ENCODING = 10,
  FPP_STATUS_HEADER = 11,
  FPP_STATUS_VERSION = 12,
  FPP_STATUS_CONTEXT = 13,
  FPP_STATUS_UNKNOWN_KEY = 14,
  FPP_STATUS_ROLE = 15,
  FPP_STATUS_ALGORITHM = 16,
  FPP_STATUS_SIGNATURE = 17,
  FPP_STATUS_SCHEMA = 18,
  // An external signer's callback failed, or returned a signature that
  // does not verify under its public key (`fpp_signer_external`).
  FPP_STATUS_SIGNER_FAILED = 19,
  // Tokens (`fpp_ar_verify`): past `exp` (with the §13 skew).
  FPP_STATUS_TOKEN_EXPIRED = 20,
  // `iat` in the future (with the §13 skew).
  FPP_STATUS_TOKEN_NOT_YET_VALID = 21,
  // Bound (`cnf`) to another session key than the one proven.
  FPP_STATUS_TOKEN_BINDING = 22,
  // Valid, but the device tier is below the minimum asked for.
  FPP_STATUS_TOKEN_TIER = 23,
  // For another server or match (SAT `aud`/`match_id`; a SAR naming
  // another instance), or its slot is taken.
  FPP_STATUS_TOKEN_AUDIENCE = 24,
  // A SAR that does not continue the chain (`seq`/`prev`).
  FPP_STATUS_TOKEN_CHAIN = 25,
  // The SAT does not name this AR (`ar_cti`).
  FPP_STATUS_TOKEN_AR_LINK = 26,
  // A subject (token, device, account, session key, build) is revoked.
  FPP_STATUS_TOKEN_REVOKED = 27,
  // The AR's client build is not one the server admits.
  FPP_STATUS_TOKEN_BUILD = 28,
  // P2P sessions (`fpp_p2p_*`): why a datagram was dropped or a call
  // refused. Drop the datagram and carry on; none of these is fatal.
  // Not a packet of this protocol, or too large.
  FPP_STATUS_P2P_MALFORMED = 30,
  // No session with that receiver index (stale, or never existed).
  FPP_STATUS_P2P_UNKNOWN_SESSION = 31,
  // Packet counter already seen or older than the replay window.
  FPP_STATUS_P2P_REPLAY = 32,
  // Authentication failed (wrong keys, or tampered).
  FPP_STATUS_P2P_DECRYPT = 33,
  // Noise handshake failed (e.g. the joiner used another host key).
  FPP_STATUS_P2P_HANDSHAKE = 34,
  // The join did not carry the host's invite secret.
  FPP_STATUS_P2P_INVITE = 35,
  // The joiner's session-key proof (AdmitPop) is invalid.
  FPP_STATUS_P2P_BINDING = 36,
  // The host has no free player slot.
  FPP_STATUS_P2P_FULL = 37,
  // Not valid in the current state (e.g. sending before connected).
  FPP_STATUS_P2P_STATE = 38,
  // Packet counter limit reached; join again.
  FPP_STATUS_P2P_EXHAUSTED = 39,
  // Payload, hello or attestation above its limit.
  FPP_STATUS_P2P_TOO_LARGE = 40,
  // No such peer.
  FPP_STATUS_P2P_UNKNOWN_PEER = 41,
  // Reliable channel full (64 unacknowledged messages); retry after a tick.
  FPP_STATUS_P2P_CONGESTED = 42,
  // Host under load and the join's cookie is missing or wrong (dropped).
  FPP_STATUS_P2P_COOKIE = 43,
  // `fpp_gs_link_*`: Server Liveness unreachable, refused the join, or
  // the link is gone.
  FPP_STATUS_GS_LINK = 50,
  // A bug in the SDK (a caught panic). Please report it.
  FPP_STATUS_INTERNAL = 99,
} FppStatus;

// What `fpp_admission_revocation` did with an event.
typedef enum FppRevocationOutcome {
  // Expired, or an action that neither refuses nor removes players.
  FPP_REVOCATION_OUTCOME_IGNORED = 0,
  // Refused from now on; players already admitted stay.
  FPP_REVOCATION_OUTCOME_RECORDED = 1,
  // Recorded, and any admitted players it names are queued for removal
  // (`fpp_admission_poll_removed`).
  FPP_REVOCATION_OUTCOME_REMOVING = 2,
  // Not in force yet: applied by `fpp_admission_tick` when it is.
  FPP_REVOCATION_OUTCOME_SCHEDULED = 3,
  // It revokes this server instance: end the match.
  FPP_REVOCATION_OUTCOME_INSTANCE_REVOKED = 4,
} FppRevocationOutcome;

// `FppControl.kind`: the §7.2 message types the fpp-session profile uses.
typedef enum FppControlKind {
  // data = SAT ‖ AR (`first_len`, `second_len`); the PoP is the handshake.
  FPP_CONTROL_KIND_ADMIT = 3,
  // `slot`, `start_tick`.
  FPP_CONTROL_KIND_ADMITTED = 4,
  // `code`.
  FPP_CONTROL_KIND_REJECT = 5,
  // data = the SAR.
  FPP_CONTROL_KIND_SAR_UPDATE = 6,
  // `code`.
  FPP_CONTROL_KIND_KICK = 10,
  FPP_CONTROL_KIND_BYE = 11,
  // data = the signed Checkpoint.
  FPP_CONTROL_KIND_CHECKPOINT_HEAD = 12,
  // data = the signed InputCommit.
  FPP_CONTROL_KIND_INPUT_COMMIT = 13,
} FppControlKind;

#if defined(FPP_GS_LINK)
// `FppGsEvent.kind`.
typedef enum FppGsEventKind {
#if defined(FPP_GS_LINK)
  // data = the next SAR, already checked: it continues the chain and
  // certifies this server's keys. Send it to every player
  // (`fpp_control_sar_update`).
  FPP_GS_EVENT_KIND_SAR = 1,
#endif
#if defined(FPP_GS_LINK)
  // data = a signed RevocationEvent (`fpp_admission_revocation`).
  FPP_GS_EVENT_KIND_REVOCATION = 2,
#endif
#if defined(FPP_GS_LINK)
  // The link is gone (`reason`): the server is no longer blessed. End
  // the match; players drop on their own once its SARs stop.
  FPP_GS_EVENT_KIND_CLOSED = 3,
#endif
} FppGsEventKind;
#endif

// What a poll returned (`FppP2pEvent.kind`).
typedef enum FppP2pEventKind {
  // Host: a player joined. `peer`; `key` = its Ed25519 session key (verify
  // its InputCommits with it), or a P-256 session key's 32-byte id (get
  // the key with `fpp_p2p_host_peer_session_key`); data = attestation ‖
  // admit_pop ‖ hello.
  FPP_P2P_EVENT_KIND_PEER_JOINED = 1,
  // Host (`peer` set) or joiner: an application datagram; data = payload.
  FPP_P2P_EVENT_KIND_DATA = 2,
  // Host: `peer`'s address changed after it answered a path challenge.
  FPP_P2P_EVENT_KIND_PEER_MIGRATED = 3,
  // Host: `peer` left with `reason`.
  FPP_P2P_EVENT_KIND_PEER_LEFT = 4,
  // Joiner: connected. `has_key`/`key` = the host's Checkpoint key;
  // data = the host's hello.
  FPP_P2P_EVENT_KIND_CONNECTED = 5,
  // Joiner: the host's address changed after it answered a path challenge.
  FPP_P2P_EVENT_KIND_HOST_MIGRATED = 6,
  // Joiner: the host closed the session with `reason`.
  FPP_P2P_EVENT_KIND_CLOSED = 7,
  // Host (`peer` set) or joiner: a reliable-channel message, delivered
  // once and in order; data = payload.
  FPP_P2P_EVENT_KIND_MESSAGE = 8,
} FppP2pEventKind;

// A server's admission state for one match.
typedef struct FppAdmission FppAdmission;

// Accumulates a host's commitment for one match epoch (04-protocol.md §8.1).
typedef struct FppCheckpointBuilder FppCheckpointBuilder;

#if defined(FPP_GS_LINK)
// A server's link to Server Liveness.
typedef struct FppGsLink FppGsLink;
#endif

// Accumulates one player's input frames for one epoch (04-protocol.md §7.4).
typedef struct FppInputCommitBuilder FppInputCommitBuilder;

// The keys tokens and revocation events are checked against.
typedef struct FppKeys FppKeys;

// The hosting player's endpoint.
typedef struct FppP2pHost FppP2pHost;

// A joining player's endpoint.
typedef struct FppP2pJoiner FppP2pJoiner;

// A server's SAR chain.
typedef struct FppSarChain FppSarChain;

// An Ed25519 signing key (a player's session key or a host's instance key),
// held here or outside the SDK (`fpp_signer_external`).
typedef struct FppSigner FppSigner;

// Signs `len` bytes at `msg` with an Ed25519 key held outside the SDK (an
// Android Keystore key, a TPM), writing the 64-byte signature to `sig_out`.
// Returns 0 on success. Called synchronously on the thread that called the
// SDK function; it may block (secure hardware can take tens of ms).
typedef int (*FppSignCallback)(void *ctx, const uint8_t *msg, size_t len, uint8_t *sig_out);

// Fields of a verified InputCommit, plus its object digest.
typedef struct FppInputCommitInfo {
  uint8_t match_id[16];
  uint16_t slot;
  uint32_t epoch;
  uint32_t first_tick;
  uint32_t last_tick;
  uint32_t n;
  uint8_t frames_root[32];
  uint8_t prev[32];
  uint8_t digest[32];
} FppInputCommitInfo;

// Fields of a verified Checkpoint, plus its object digest.
typedef struct FppCheckpointInfo {
  uint8_t match_id[16];
  uint8_t gs_instance_id[32];
  uint8_t build_id[32];
  uint64_t policy_ver;
  uint32_t epoch;
  uint32_t first_tick;
  uint32_t last_tick;
  uint8_t prev[32];
  uint8_t inputs_root[32];
  uint32_t inputs_n;
  uint8_t events_root[32];
  uint32_t events_n;
  uint8_t state_root[32];
  uint8_t rng_root[32];
  uint32_t rng_n;
  uint8_t roster_root[32];
  uint32_t roster_n;
  uint8_t digest[32];
} FppCheckpointInfo;

// Fields of a verified Attestation Result (04-protocol.md §6.1).
typedef struct FppArInfo {
  // Device tier, 0..3 (D0..D3).
  uint8_t tier;
  // `FPP_FEATURE_*` bits.
  uint32_t features;
  uint64_t iat;
  uint64_t exp;
  uint64_t policy_ver;
  uint8_t did[32];
  uint8_t client_build[32];
  uint8_t cti[16];
  // NUL-terminated, e.g. "windows", "android", "ios".
  uint8_t platform[33];
} FppArInfo;

// The current SAR of a chain.
typedef struct FppSarInfo {
  // `gs_instance_id`: the SAT's `aud` must name it.
  uint8_t sub[32];
  // The instance key: the server's Checkpoints verify under it
  // (`fpp_verify_checkpoint`).
  uint8_t cnf[32];
  // 1 if the SAR binds an `fpp_p2p_*` endpoint: its static X25519 key,
  // which must be the key the player dialled.
  uint8_t has_noise_static;
  uint8_t noise_static[32];
  // The server's build, as Server Liveness measured it.
  uint8_t build_id[32];
  uint8_t server_class;
  uint64_t iat;
  uint64_t exp;
  uint64_t seq;
  // NUL-terminated.
  uint8_t region[33];
} FppSarInfo;

// A joiner the server admitted, or (`reason` set) why it did not.
typedef struct FppAdmitted {
  // `fpp_types::Reason` code to send in `Reject` and close the session
  // with; 0 when admitted.
  uint16_t reason;
  // The SAT's slot (the Broker placed the player there).
  uint16_t slot;
  // Device tier of the AR, 0..3.
  uint8_t tier;
  // Device ID (stable per device: what a ban names, finding H08).
  uint8_t did[32];
  // The SAT's account (`sub`).
  uint8_t account[32];
  // The AR's measured client build (finding H07).
  uint8_t client_build[32];
  uint8_t sat_cti[16];
  uint64_t sat_exp;
  // NUL-terminated.
  uint8_t platform[33];
  // NUL-terminated.
  uint8_t queue[65];
} FppAdmitted;

// A decoded control message. Byte fields go to the caller's data buffer.
typedef struct FppControl {
  enum FppControlKind kind;
  uint16_t code;
  uint16_t slot;
  uint32_t start_tick;
  size_t first_len;
  size_t second_len;
} FppControl;

#if defined(FPP_GS_LINK)
// What the server joins with.
typedef struct FppGsLinkConfig {
  // Server Liveness, "ip:port".
  const char *liveness;
  // The CA (DER file) Server Liveness's TLS certificate must chain to.
  const char *ca_cert;
  // The regional key bundle (JSON file): SARs and revocation events are
  // checked under it.
  const char *bundle;
  // A label for this server.
  const char *gs_id;
  // The address players dial, "ip:port" (the Broker hands it out).
  const char *game_addr;
  // 32-byte seed of the server's long-term Ed25519 key: Server Liveness
  // knows the server by it.
  const uint8_t *gs_key_seed;
  // 32-byte Ed25519 key that signs this run's Checkpoints (an
  // `FppSigner`'s public key); every SAR certifies it.
  const uint8_t *instance_public_key;
  // 32-byte static X25519 key of the server's `fpp_p2p_host`
  // (`fpp_p2p_public_key`); every SAR binds it, and players dial it.
  const uint8_t *noise_public_key;
  // 32-byte SHA-256 of the server's executable, or NULL to hash the
  // running one. With `tpm2`, Server Liveness uses the kernel's
  // measurement instead.
  const uint8_t *sw_hash;
  // 1: prove the server's boot and build with a TPM 2.0 through
  // tpm2-tools (as `gs-sim --tpm2`).
  uint8_t tpm2;
  // Give up joining after this long (0: 10 s).
  uint32_t timeout_ms;
} FppGsLinkConfig;
#endif

#if defined(FPP_GS_LINK)
typedef struct FppGsEvent {
  enum FppGsEventKind kind;
  // `fpp_types::Reason` code (Closed).
  uint16_t reason;
  size_t data_len;
} FppGsEvent;
#endif

// One event. Variable-size fields go into the caller's data buffer; the
// `*_len` fields say how to split it.
typedef struct FppP2pEvent {
  enum FppP2pEventKind kind;
  uint32_t peer;
  // `fpp_types::Reason` code (PeerLeft, Closed).
  uint16_t reason;
  uint8_t has_key;
  uint8_t key[32];
  // PeerJoined: the first `attestation_len` data bytes are the joiner's
  // Attestation Result (0 = none, device tier D0). Not verified by the SDK.
  size_t attestation_len;
  // PeerJoined: the next `admit_pop_len` bytes are its signed AdmitPop
  // (keep it in the match's evidence bundle).
  size_t admit_pop_len;
  // Total bytes written to the data buffer.
  size_t data_len;
} FppP2pEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// ABI version of this header. Increments on any incompatible change.
uint32_t fpp_abi_version(void);

// Static, human-readable name of a status code (never NULL).
const char *fpp_status_str(int status);

// SHA-256 of `data`.
//
// # Safety
// `data` valid for `len` bytes (or NULL with `len` 0); `out` valid for 32 bytes.
enum FppStatus fpp_sha256(const uint8_t *data, size_t len, uint8_t *out);

// Digest of a signed object (its exact bytes): the value for `prev` links and
// for InputLeaf commit references.
//
// # Safety
// `object` valid for `len` bytes; `out` valid for 32 bytes.
enum FppStatus fpp_object_digest(const uint8_t *object, size_t len, uint8_t *out);

// The challenge a device binds its platform evidence to (roadmap P3):
// `SHA-256("fpp/1/attest-challenge" || 0x00 || verifier_challenge || session_pub)`.
// Pass it to Android `KeyGenParameterSpec.Builder.setAttestationChallenge`
// or as the App Attest `clientDataHash`. Evidence made for another admission
// challenge or another session key does not verify.
//
// # Safety
// `verifier_challenge`, `session_pub` and `out` valid for 32 bytes each.
enum FppStatus fpp_attest_challenge(const uint8_t *verifier_challenge,
                                    const uint8_t *session_pub,
                                    uint8_t *out);

// The challenge for a key that will itself be the session key (an Android
// Keystore key, Ed25519 in the TEE or P-256 in the TEE or StrongBox): it
// is attested when it is made, so its public key cannot be in the
// challenge. The Verifier then requires the attested key to be the
// session key. `SHA-256("fpp/1/attest-challenge" || 0x00 || verifier_challenge)`.
//
// # Safety
// `verifier_challenge` and `out` valid for 32 bytes each.
enum FppStatus fpp_attest_challenge_hw_key(const uint8_t *verifier_challenge, uint8_t *out);

// [`fpp_attest_challenge`] for a session key of either kind
// (`fpp_signer_session_key`: 32 or 65 bytes).
//
// # Safety
// `verifier_challenge` and `out` valid for 32 bytes; `session_key` valid
// for `session_key_len` bytes.
enum FppStatus fpp_attest_challenge_key(const uint8_t *verifier_challenge,
                                        const uint8_t *session_key,
                                        size_t session_key_len,
                                        uint8_t *out);

// The evidence envelope for an Android Keystore key attestation: the
// attested key's certificate chain, leaf first
// (`KeyStore.getCertificateChain`, each `Certificate.getEncoded()`), for
// `ClientAdmissionRequest.evidence`.
//
// # Safety
// `certs` and `lens` valid for `count` entries; each `certs[i]` valid for
// `lens[i]` bytes. `out_len` valid for a write; `out` NULL or valid for `cap`.
enum FppStatus fpp_evidence_android_key(const uint8_t *const *certs,
                                        const size_t *lens,
                                        size_t count,
                                        uint8_t *out,
                                        size_t cap,
                                        size_t *out_len);

// [`fpp_evidence_android_key`] with a Play Integrity token (the string
// `IntegrityTokenResponse.token()` gives), requested with
// `nonce = base64url(fpp_attest_challenge_key(verifier_challenge,
// session_key))` (no padding). A Verifier with the app's response keys
// needs a `MEETS_STRONG_INTEGRITY` verdict for tier D2.
//
// # Safety
// As [`fpp_evidence_android_key`]; `token` valid for `token_len` bytes of
// UTF-8.
enum FppStatus fpp_evidence_android_key_integrity(const uint8_t *const *certs,
                                                  const size_t *lens,
                                                  size_t count,
                                                  const uint8_t *token,
                                                  size_t token_len,
                                                  uint8_t *out,
                                                  size_t cap,
                                                  size_t *out_len);

// The evidence envelope for an Apple App Attest attestation object (from
// `DCAppAttestService.attestKey`, made with `fpp_attest_challenge` as the
// client data hash). Send it once per app key; later admissions send
// assertions (`fpp_evidence_apple_assert`).
//
// # Safety
// `attestation` valid for `len` bytes; `out_len` valid for a write; `out`
// NULL or valid for `cap` bytes.
enum FppStatus fpp_evidence_apple_attest(const uint8_t *attestation,
                                         size_t len,
                                         uint8_t *out,
                                         size_t cap,
                                         size_t *out_len);

// The evidence envelope for an Apple App Attest assertion (from
// `DCAppAttestService.generateAssertion`, with `fpp_attest_challenge` as the
// client data hash) by the attested key `key_id` (32 bytes, base64-decoded).
//
// # Safety
// `key_id` valid for 32 bytes; `assertion` valid for `len` bytes; `out_len`
// valid for a write; `out` NULL or valid for `cap` bytes.
enum FppStatus fpp_evidence_apple_assert(const uint8_t *key_id,
                                         const uint8_t *assertion,
                                         size_t len,
                                         uint8_t *out,
                                         size_t cap,
                                         size_t *out_len);

// Generate a fresh key from the OS random number generator.
//
// # Safety
// `out` valid for a pointer write. Free the result with `fpp_signer_free`.
enum FppStatus fpp_signer_generate(struct FppSigner **out);

// Recreate a key from a 32-byte seed (deterministic; for tests and for keys
// the game persists itself).
//
// # Safety
// `seed` valid for 32 bytes; `out` valid for a pointer write.
enum FppStatus fpp_signer_from_seed(const uint8_t *seed, struct FppSigner **out);

// A key held outside the SDK: its 32-byte Ed25519 public key and a callback
// that signs with it (an Android 13+ Keystore Ed25519 key, attested in the
// TEE, is then the session key itself: tier D2, docs 10 §4). Every signature
// the callback returns is verified; one that fails, or a non-zero return,
// makes the signing call return `FPP_STATUS_SIGNER_FAILED` and emit nothing.
// `ctx` is passed back to the callback unchanged and must outlive the handle.
//
// # Safety
// `public_key` valid for 32 bytes; `callback` safe to call as documented at
// `FppSignCallback`; `out` valid for a pointer write.
enum FppStatus fpp_signer_external(const uint8_t *public_key,
                                   FppSignCallback callback,
                                   void *ctx,
                                   struct FppSigner **out);

// [`fpp_signer_external`] for an ECDSA P-256 session key (ES256): a key in
// a TPM, the Secure Enclave or StrongBox, which have no Ed25519.
// `public_key` is the uncompressed SEC1 point (`0x04 ‖ x ‖ y`, 65 bytes);
// the callback writes the signature as `r ‖ s` (64 bytes, big-endian; not
// DER), over SHA-256 of the message as ES256 defines. Either `s` is
// accepted; the SDK emits the low one.
//
// # Safety
// `public_key` valid for 65 bytes; `callback` safe to call as documented at
// `FppSignCallback`; `out` valid for a pointer write.
enum FppStatus fpp_signer_external_p256(const uint8_t *public_key,
                                        FppSignCallback callback,
                                        void *ctx,
                                        struct FppSigner **out);

// # Safety
// `signer` NULL or a live handle; not used afterwards.
void fpp_signer_free(struct FppSigner *signer);

// The key's 32-byte Ed25519 public key (what peers need to verify it).
// `FPP_STATUS_INVALID_ARGUMENT` for a P-256 key: use
// [`fpp_signer_session_key`].
//
// # Safety
// `signer` a live handle; `out` valid for 32 bytes.
enum FppStatus fpp_signer_public_key(const struct FppSigner *signer, uint8_t *out);

// The key as a session key: 32 bytes for Ed25519, 65 (`0x04 ‖ x ‖ y`) for
// P-256. This is what `fpp_attest_challenge_key`, `fpp_verify_input_commit_key`
// and `fpp_ar_verify_key` take, and what the Verifier binds the AR to.
//
// # Safety
// `signer` a live handle; `out` valid for `FPP_SESSION_KEY_MAX` bytes;
// `out_len` valid for a write.
enum FppStatus fpp_signer_session_key(const struct FppSigner *signer,
                                      uint8_t *out,
                                      size_t *out_len);

// SHA-256 of a public key's COSE_Key: the `gs_instance_id` of a host key.
// The first 16 bytes are the key's `kid`.
//
// # Safety
// `public_key` valid for 32 bytes; `out` valid for 32 bytes.
enum FppStatus fpp_key_digest(const uint8_t *public_key, uint8_t *out);

// Start an epoch's commitment. `match_id`: 16 bytes. `prev`: 32 bytes, the
// digest of this player's previous signed InputCommit, or NULL at epoch 0.
// Requires `first_tick <= last_tick`.
//
// # Safety
// Pointers valid as documented; `out` valid for a pointer write.
enum FppStatus fpp_input_commit_begin(const uint8_t *match_id,
                                      uint16_t slot,
                                      uint32_t epoch,
                                      uint32_t first_tick,
                                      uint32_t last_tick,
                                      const uint8_t *prev,
                                      struct FppInputCommitBuilder **out);

// Add the frame (title-defined intent bytes) sent for `tick`. Ticks must be
// strictly ascending and inside the epoch's range.
//
// # Safety
// `builder` a live handle; `payload` valid for `len` bytes.
enum FppStatus fpp_input_commit_add_frame(struct FppInputCommitBuilder *builder,
                                          uint32_t tick,
                                          const uint8_t *payload,
                                          size_t len);

// Merkle root of the frames added so far. A host builds one from the frames
// it received and compares it with the player's signed `frames_root`.
//
// # Safety
// `builder` a live handle; `out` valid for 32 bytes.
enum FppStatus fpp_input_commit_frames_root(const struct FppInputCommitBuilder *builder,
                                            uint8_t *out);

// Sign the commitment with the player's session key. Does not consume the
// builder; signing is deterministic, so a size query followed by a second
// call yields the same bytes.
//
// # Safety
// Handles live; `out` valid for `cap` bytes or NULL; `out_len` valid.
enum FppStatus fpp_input_commit_sign(const struct FppInputCommitBuilder *builder,
                                     const struct FppSigner *session_key,
                                     uint8_t *out,
                                     size_t cap,
                                     size_t *out_len);

// # Safety
// `builder` NULL or a live handle; not used afterwards.
void fpp_input_commit_free(struct FppInputCommitBuilder *builder);

// Start a checkpoint. `match_id`: 16 bytes; `build_id`: 32 bytes; `prev`: 32
// bytes (digest of the previous signed Checkpoint) or NULL at epoch 0.
//
// # Safety
// Pointers valid as documented; `out` valid for a pointer write.
enum FppStatus fpp_checkpoint_begin(const uint8_t *match_id,
                                    const uint8_t *build_id,
                                    uint64_t policy_ver,
                                    uint32_t epoch,
                                    uint32_t first_tick,
                                    uint32_t last_tick,
                                    const uint8_t *prev,
                                    struct FppCheckpointBuilder **out);

// Add one player slot's input record, in strictly ascending slot order.
// `commit_digest`: 32 bytes (`fpp_object_digest` of the player's signed
// InputCommit) or NULL if none arrived. `applied`: bitset over the epoch's
// ticks, bit i (LSB-first per byte) set when the frame for `first_tick + i`
// was applied in time; exactly `ceil(ticks / 8)` bytes.
//
// # Safety
// `builder` a live handle; pointers valid as documented.
enum FppStatus fpp_checkpoint_add_input(struct FppCheckpointBuilder *builder,
                                        uint16_t slot,
                                        const uint8_t *commit_digest,
                                        const uint8_t *applied,
                                        size_t applied_len);

// Append an authoritative event (title-defined bytes), in simulation order.
//
// # Safety
// `builder` a live handle; `data` valid for `len` bytes.
enum FppStatus fpp_checkpoint_add_event(struct FppCheckpointBuilder *builder,
                                        const uint8_t *data,
                                        size_t len);

// Append a VRF proof for an outcome roll made this epoch.
//
// # Safety
// `builder` a live handle; `data` valid for `len` bytes.
enum FppStatus fpp_checkpoint_add_rng(struct FppCheckpointBuilder *builder,
                                      const uint8_t *data,
                                      size_t len);

// Append a roster entry (slot, admission token id, device id) for an admitted player.
//
// # Safety
// `builder` a live handle; `data` valid for `len` bytes.
enum FppStatus fpp_checkpoint_add_roster(struct FppCheckpointBuilder *builder,
                                         const uint8_t *data,
                                         size_t len);

// Set the digest of the canonical audit-projection state at `last_tick`
// (32 bytes). Defaults to all zeros for titles without an audit projection yet.
//
// # Safety
// `builder` a live handle; `root` valid for 32 bytes.
enum FppStatus fpp_checkpoint_set_state_root(struct FppCheckpointBuilder *builder,
                                             const uint8_t *root);

// Sign the checkpoint with the host's instance key. `gs_instance_id` is
// derived from that key. Does not consume the builder.
//
// # Safety
// Handles live; `out` valid for `cap` bytes or NULL; `out_len` valid.
enum FppStatus fpp_checkpoint_sign(const struct FppCheckpointBuilder *builder,
                                   const struct FppSigner *instance_key,
                                   uint8_t *out,
                                   size_t cap,
                                   size_t *out_len);

// # Safety
// `builder` NULL or a live handle; not used afterwards.
void fpp_checkpoint_free(struct FppCheckpointBuilder *builder);

// Verify a signed InputCommit against a player's 32-byte session public key.
// On success fills `*info` if it is not NULL.
//
// # Safety
// `object` valid for `len` bytes; `session_public_key` valid for 32 bytes;
// `info` NULL or valid for a write.
enum FppStatus fpp_verify_input_commit(const uint8_t *object,
                                       size_t len,
                                       const uint8_t *session_public_key,
                                       struct FppInputCommitInfo *info);

// [`fpp_verify_input_commit`] for a session key of either kind (32 bytes
// Ed25519, or 65 bytes P-256: `fpp_p2p_host_peer_session_key`).
//
// # Safety
// `object` valid for `len` bytes; `session_key` valid for
// `session_key_len` bytes; `info` NULL or valid for a write.
enum FppStatus fpp_verify_input_commit_key(const uint8_t *object,
                                           size_t len,
                                           const uint8_t *session_key,
                                           size_t session_key_len,
                                           struct FppInputCommitInfo *info);

// Verify a signed Checkpoint against a host's 32-byte instance public key,
// and check that `gs_instance_id` names that key. On success fills `*info`
// if it is not NULL.
//
// # Safety
// `object` valid for `len` bytes; `instance_public_key` valid for 32 bytes;
// `info` NULL or valid for a write.
enum FppStatus fpp_verify_checkpoint(const uint8_t *object,
                                     size_t len,
                                     const uint8_t *instance_public_key,
                                     struct FppCheckpointInfo *info);

// Appraise a joiner's Attestation Result where it is admitted (a game
// server, or a player host with a trust policy): signed by one of
// `verifier_key_count` 32-byte Verifier public keys at `verifier_keys`,
// valid at `now_s` (Unix seconds, ±60 s), bound to `session_public_key`
// (the key the joiner proved in the handshake: `FppP2pEvent.key`), and of
// tier `minimum_tier` or above. Fills `*info` (if not NULL) whenever the
// token verifies, so a caller refusing on `FPP_STATUS_TOKEN_TIER` can say
// which tier it had.
//
// # Safety
// `ar` valid for `len` bytes; `verifier_keys` valid for
// `32 * verifier_key_count` bytes; `session_public_key` valid for 32 bytes;
// `info` NULL or valid for a write.
enum FppStatus fpp_ar_verify(const uint8_t *ar,
                             size_t len,
                             const uint8_t *verifier_keys,
                             size_t verifier_key_count,
                             const uint8_t *session_public_key,
                             uint64_t now_s,
                             uint8_t minimum_tier,
                             struct FppArInfo *info);

// [`fpp_ar_verify`] for a session key of either kind (32 bytes Ed25519,
// or 65 bytes P-256: `fpp_p2p_host_peer_session_key`).
//
// # Safety
// As [`fpp_ar_verify`], with `session_key` valid for `session_key_len`
// bytes.
enum FppStatus fpp_ar_verify_key(const uint8_t *ar,
                                 size_t len,
                                 const uint8_t *verifier_keys,
                                 size_t verifier_key_count,
                                 const uint8_t *session_key,
                                 size_t session_key_len,
                                 uint64_t now_s,
                                 uint8_t minimum_tier,
                                 struct FppArInfo *info);

// An empty key set. Free it with `fpp_keys_free`.
//
// # Safety
// `out` valid for a pointer write.
enum FppStatus fpp_keys_new(struct FppKeys **out);

// Add a 32-byte Ed25519 public key in `role` (`FPP_KEY_*`). A role may hold
// several keys (rotation).
//
// # Safety
// `keys` a live handle; `public_key` valid for 32 bytes.
enum FppStatus fpp_keys_add(struct FppKeys *keys, uint32_t role, const uint8_t *public_key);

// # Safety
// `keys` NULL or a live handle, not used afterwards.
void fpp_keys_free(struct FppKeys *keys);

// Start a chain from a server's first SAR, checked under `keys`' Server
// Liveness keys at `now_s` (Unix seconds). The caller then checks that it
// is for the server it meant (`fpp_sar_chain_info`: `noise_static` is the
// key it dialled, `sub` its SAT's audience).
//
// # Safety
// `keys` a live handle; `sar` valid for `len` bytes; `out` valid for a
// pointer write.
enum FppStatus fpp_sar_chain_start(const struct FppKeys *keys,
                                   const uint8_t *sar,
                                   size_t len,
                                   uint64_t now_s,
                                   struct FppSarChain **out);

// Extend the chain with the server's next SAR. Any error means the
// server lost its blessing: end the session (`SAR_LAPSED`, 7). The chain
// is unchanged on error.
//
// # Safety
// `chain` a live handle; `sar` valid for `len` bytes.
enum FppStatus fpp_sar_chain_update(struct FppSarChain *chain,
                                    const uint8_t *sar,
                                    size_t len,
                                    uint64_t now_s);

// `FPP_STATUS_OK` while the current SAR is valid at `now_s`, else
// `FPP_STATUS_TOKEN_EXPIRED`. (Also count time since the last SAR on your
// own clock: no update for three issue intervals is a lapse, 04 §6.3.)
//
// # Safety
// `chain` a live handle.
enum FppStatus fpp_sar_chain_live(const struct FppSarChain *chain, uint64_t now_s);

// The chain's current SAR.
//
// # Safety
// `chain` a live handle; `info` valid for a write.
enum FppStatus fpp_sar_chain_info(const struct FppSarChain *chain, struct FppSarInfo *info);

// # Safety
// `chain` NULL or a live handle, not used afterwards.
void fpp_sar_chain_free(struct FppSarChain *chain);

// Admission for match `match_id` on the server whose instance key is
// `instance_public_key` (the SAT's `aud` must name it), against `keys`'
// Broker and Verifier keys (copied), refusing ARs below `minimum_tier`.
//
// # Safety
// `keys` a live handle; `instance_public_key` valid for 32 bytes;
// `match_id` valid for 16 bytes; `out` valid for a pointer write.
enum FppStatus fpp_admission_new(const struct FppKeys *keys,
                                 const uint8_t *instance_public_key,
                                 const uint8_t *match_id,
                                 uint8_t minimum_tier,
                                 struct FppAdmission **out);

// Admit only ARs whose measured client build is one of those added
// (finding H07: a modified client cannot claim a release build where the
// platform measures it). None added: any build.
//
// # Safety
// `admission` a live handle; `build_id` valid for 32 bytes.
enum FppStatus fpp_admission_add_client_build(struct FppAdmission *admission,
                                              const uint8_t *build_id);

// Refuse a device by its Device ID (a title's own ban list; finding H08:
// the ID comes from the AR, which the Verifier derives from hardware where
// the platform has it). An admitted player on that device is queued for
// removal.
//
// # Safety
// `admission` a live handle; `did` valid for 32 bytes.
enum FppStatus fpp_admission_ban_device(struct FppAdmission *admission, const uint8_t *did);

// §7.2 admission of a joiner that proved `session_key` in its handshake
// (`fpp_p2p_host_peer_session_key`), presenting `sat` and `ar` in `Admit`,
// at `now_s`. On success the player holds the SAT's slot until
// `fpp_admission_remove`, and the SAT cannot be used again in this match.
// `*out` is always filled: `reason` says what to send in `Reject` when the
// status is not OK (a taken slot is `SAT_INVALID`).
//
// # Safety
// `admission` a live handle; `sat`, `ar` and `session_key` valid for their
// lengths; `out` valid for a write.
enum FppStatus fpp_admission_admit(struct FppAdmission *admission,
                                   const uint8_t *sat,
                                   size_t sat_len,
                                   const uint8_t *ar,
                                   size_t ar_len,
                                   const uint8_t *session_key,
                                   size_t session_key_len,
                                   uint64_t now_s,
                                   struct FppAdmitted *out);

// The player in `slot` left: the slot is free (its SAT stays used).
//
// # Safety
// `admission` a live handle.
enum FppStatus fpp_admission_remove(struct FppAdmission *admission, uint16_t slot);

// A signed RevocationEvent from the Revocation Feed (Server Liveness
// relays them to its game servers: `fpp_gs_link_poll`), checked under
// `keys`' Enforcement keys and applied at `now_s`. `*outcome` (if not
// NULL) says what to do next.
//
// # Safety
// `admission` a live handle; `event` valid for `len` bytes; `outcome` NULL
// or valid for a write.
enum FppStatus fpp_admission_revocation(struct FppAdmission *admission,
                                        const uint8_t *event,
                                        size_t len,
                                        uint64_t now_s,
                                        enum FppRevocationOutcome *outcome);

// Apply scheduled revocation events now in force. Call about once a
// second. Returns `FPP_STATUS_TOKEN_REVOKED` if one revoked this server
// instance (end the match); players removed are queued as with
// `fpp_admission_revocation`.
//
// # Safety
// `admission` a live handle.
enum FppStatus fpp_admission_tick(struct FppAdmission *admission, uint64_t now_s);

// Next admitted player a revocation (or a device ban) removed: its slot
// and the reason code to kick it with. `FPP_STATUS_EMPTY` when none.
//
// # Safety
// `admission` a live handle; `slot` and `reason` valid for writes.
enum FppStatus fpp_admission_poll_removed(struct FppAdmission *admission,
                                          uint16_t *slot,
                                          uint16_t *reason);

// # Safety
// `admission` NULL or a live handle, not used afterwards.
void fpp_admission_free(struct FppAdmission *admission);

// Decode one control message from the reliable channel. Byte fields are
// copied to `(data, cap)` back to back (`first_len`, then `second_len`);
// `FPP_STATUS_BUFFER_TOO_SMALL` if they do not fit (`*out` holds the
// lengths). A message type the fpp-session profile does not use is
// `FPP_STATUS_SCHEMA`.
//
// # Safety
// `message` valid for `len` bytes; `out` valid for a write; `data` NULL or
// valid for `cap` bytes.
enum FppStatus fpp_control_decode(const uint8_t *message,
                                  size_t len,
                                  struct FppControl *out,
                                  uint8_t *data,
                                  size_t cap);

// `SarUpdate{sar}`: the server sends it first to every joiner, and every
// new SAR to every player.
//
// # Safety
// `sar` valid for `len` bytes; output per the SDK's convention.
enum FppStatus fpp_control_sar_update(const uint8_t *sar,
                                      size_t len,
                                      uint8_t *out,
                                      size_t cap,
                                      size_t *out_len);

// `Admit{sat, ar}` (empty PoP: the fpp-session handshake proved the key).
//
// # Safety
// `sat`, `ar` valid for their lengths; output per the SDK's convention.
enum FppStatus fpp_control_admit(const uint8_t *sat,
                                 size_t sat_len,
                                 const uint8_t *ar,
                                 size_t ar_len,
                                 uint8_t *out,
                                 size_t cap,
                                 size_t *out_len);

// `Admitted{slot, start_tick}`.
//
// # Safety
// Output per the SDK's convention.
enum FppStatus fpp_control_admitted(uint16_t slot,
                                    uint32_t start_tick,
                                    uint8_t *out,
                                    size_t cap,
                                    size_t *out_len);

// `Reject{code}` (`kick` 0) or `Kick{code}` (`kick` 1).
//
// # Safety
// Output per the SDK's convention.
enum FppStatus fpp_control_refuse(uint16_t code,
                                  uint8_t kick,
                                  uint8_t *out,
                                  size_t cap,
                                  size_t *out_len);

// `CheckpointHead{checkpoint}`: the Checkpoint the server just signed,
// for every player.
//
// # Safety
// `checkpoint` valid for `len` bytes; output per the SDK's convention.
enum FppStatus fpp_control_checkpoint_head(const uint8_t *checkpoint,
                                           size_t len,
                                           uint8_t *out,
                                           size_t cap,
                                           size_t *out_len);

// Name of a `fpp_types::Reason` code (never NULL).
const char *fpp_reason_str(uint16_t code);

#if defined(FPP_GS_LINK)
// Load a regional key bundle (`keys/fpp_key_bundle.json`, as `fpp-cell
// bundle` gathers it) into a key set for the rest of the SDK.
//
// # Safety
// `path` a NUL-terminated string; `out` valid for a pointer write.
enum FppStatus fpp_keys_load_bundle(const char *path, struct FppKeys **out);
#endif

#if defined(FPP_GS_LINK)
// Join Server Liveness and start the link. Blocks until joined (or
// `timeout_ms`). `FPP_STATUS_GS_LINK` if it cannot reach or join Server
// Liveness (it logs why to stderr).
//
// # Safety
// `config` valid, its strings NUL-terminated and its keys valid for 32
// bytes; `out` valid for a pointer write.
enum FppStatus fpp_gs_link_connect(const struct FppGsLinkConfig *config, struct FppGsLink **out);
#endif

#if defined(FPP_GS_LINK)
// The match Server Liveness gave this server: SATs name it, and the
// server's Checkpoints must (`fpp_checkpoint_begin`).
//
// # Safety
// `link` a live handle; `out` valid for 16 bytes.
enum FppStatus fpp_gs_link_match_id(const struct FppGsLink *link, uint8_t *out);
#endif

#if defined(FPP_GS_LINK)
// Next event, or `FPP_STATUS_EMPTY`. Its bytes go to `(data, cap)`; if
// they do not fit the event stays queued and `FPP_STATUS_BUFFER_TOO_SMALL`
// is returned with `event->data_len` set.
//
// # Safety
// `link` a live handle; `event` valid for a write; `data` NULL or valid
// for `cap` bytes.
enum FppStatus fpp_gs_link_poll(struct FppGsLink *link,
                                struct FppGsEvent *event,
                                uint8_t *data,
                                size_t cap);
#endif

#if defined(FPP_GS_LINK)
// Submit a signed Checkpoint (one per epoch, from epoch 0, each `prev`
// the last one's digest). Server Liveness revokes a server whose chain
// breaks or that goes quiet for 30 s, so a match sends one even in its
// lobby.
//
// # Safety
// `link` a live handle; `checkpoint` valid for `len` bytes.
enum FppStatus fpp_gs_link_submit_checkpoint(struct FppGsLink *link,
                                             const uint8_t *checkpoint,
                                             size_t len);
#endif

#if defined(FPP_GS_LINK)
// Close the link (leave Server Liveness) and free it.
//
// # Safety
// `link` NULL or a live handle, not used afterwards.
void fpp_gs_link_free(struct FppGsLink *link);
#endif

// Generate a static X25519 key pair (the host's identity for its invites).
// `private_out` and `public_out`: 32 bytes each. Keep the private key secret;
// put the public key in the invite.
//
// # Safety
// Both pointers valid for 32 writes.
enum FppStatus fpp_p2p_keypair_generate(uint8_t *private_out, uint8_t *public_out);

// The public key for a 32-byte static private key (e.g. one the game saved).
//
// # Safety
// Both pointers valid for 32 bytes.
enum FppStatus fpp_p2p_public_key(const uint8_t *private_key, uint8_t *public_out);

// Create a host. `static_private`: 32 bytes. `invite_secret`: 32 bytes that
// joiners must present, or NULL for none (it authorizes only; it is never
// used as a key). `instance_public_key`: 32-byte Ed25519 key that signs this
// host's Checkpoints, announced to joiners, or NULL. `hello`: title bytes
// for every joiner (≤ `FPP_P2P_MAX_HELLO`). `max_peers`: player limit.
//
// # Safety
// Pointers valid as documented; `out` valid for a pointer write.
enum FppStatus fpp_p2p_host_new(const uint8_t *static_private,
                                const uint8_t *invite_secret,
                                const uint8_t *instance_public_key,
                                const uint8_t *hello,
                                size_t hello_len,
                                uint32_t max_peers,
                                struct FppP2pHost **out);

// Feed one datagram received from `from`. A non-OK status means it was
// dropped (count it; do not disconnect anyone over it).
//
// # Safety
// `host` a live handle; `from` valid for `from_len`; `datagram` valid for `len`.
enum FppStatus fpp_p2p_host_recv(struct FppP2pHost *host,
                                 const uint8_t *from,
                                 size_t from_len,
                                 const uint8_t *datagram,
                                 size_t len);

// Queue an application datagram for `peer` (≤ `FPP_P2P_MAX_PAYLOAD` bytes).
//
// # Safety
// `host` a live handle; `payload` valid for `len` bytes.
enum FppStatus fpp_p2p_host_send(struct FppP2pHost *host,
                                 uint32_t peer,
                                 const uint8_t *payload,
                                 size_t len);

// Queue a message on `peer`'s reliable ordered channel (≤
// `FPP_P2P_MAX_MESSAGE` bytes): InputCommits, Checkpoint heads, events that
// must arrive. It is resent from `fpp_p2p_host_tick` until acknowledged.
// Per-tick game state belongs in `fpp_p2p_host_send` (unreliable).
//
// # Safety
// `host` a live handle; `payload` valid for `len` bytes.
enum FppStatus fpp_p2p_host_send_reliable(struct FppP2pHost *host,
                                          uint32_t peer,
                                          const uint8_t *payload,
                                          size_t len);

// Advance time (a monotonic clock in ms): queues acks and due
// retransmissions for every peer and ages join cookies. Call once per game
// tick, then drain `fpp_p2p_host_poll_transmit`.
//
// # Safety
// `host` a live handle.
enum FppStatus fpp_p2p_host_tick(struct FppP2pHost *host, uint64_t now_ms);

// Queue an empty keepalive for `peer` (when idle, to hold NAT bindings open).
//
// # Safety
// `host` a live handle.
enum FppStatus fpp_p2p_host_keepalive(struct FppP2pHost *host, uint32_t peer);

// Tell `peer` why (an `fpp_types::Reason` code, e.g. 5 = tier insufficient)
// and forget it.
//
// # Safety
// `host` a live handle.
enum FppStatus fpp_p2p_host_disconnect(struct FppP2pHost *host, uint32_t peer, uint16_t reason);

// Take the next datagram to send: its destination into `(to, to_cap)` and
// its bytes into `(packet, cap)`. Returns `FPP_STATUS_EMPTY` when none is
// queued. On `FPP_STATUS_BUFFER_TOO_SMALL` both sizes are reported and the
// datagram stays queued. Buffers of `FPP_P2P_MAX_ADDRESS` and
// `FPP_P2P_MAX_PACKET` bytes always suffice.
//
// # Safety
// `host` a live handle; `to`/`packet` NULL or valid for their capacities;
// `to_len`/`len` valid for writes.
enum FppStatus fpp_p2p_host_poll_transmit(struct FppP2pHost *host,
                                          uint8_t *to,
                                          size_t to_cap,
                                          size_t *to_len,
                                          uint8_t *packet,
                                          size_t cap,
                                          size_t *len);

// Take the next event into `*event`, with its variable-size data in
// `(data, cap)`. Returns `FPP_STATUS_EMPTY` when none is queued. On
// `FPP_STATUS_BUFFER_TOO_SMALL`, `event->data_len` holds the size needed and
// the event stays queued. A buffer of `FPP_P2P_MAX_PACKET` bytes always suffices.
//
// # Safety
// `host` a live handle; `event` valid for a write; `data` NULL or valid for `cap`.
enum FppStatus fpp_p2p_host_poll_event(struct FppP2pHost *host,
                                       struct FppP2pEvent *event,
                                       uint8_t *data,
                                       size_t cap);

// The session key `peer` proved in its handshake, 32 bytes (Ed25519) or 65
// (P-256), for `fpp_verify_input_commit_key` and `fpp_ar_verify_key`.
// (`FppP2pEvent.key` holds a P-256 key's 32-byte id, `0x02/0x03`-compressed
// point hashed, as revocations name it.)
//
// # Safety
// `host` a live handle; `out` valid for `FPP_SESSION_KEY_MAX` bytes;
// `out_len` valid for a write.
enum FppStatus fpp_p2p_host_peer_session_key(const struct FppP2pHost *host,
                                             uint32_t peer,
                                             uint8_t *out,
                                             size_t *out_len);

// Number of joined players.
//
// # Safety
// `host` a live handle; `out` valid for a write.
enum FppStatus fpp_p2p_host_peer_count(const struct FppP2pHost *host, uint32_t *out);

// # Safety
// `host` NULL or a live handle; not used afterwards.
void fpp_p2p_host_free(struct FppP2pHost *host);

// Start joining the host at `host_addr`. `host_static_public`: 32 bytes from
// the invite (never from the network). `invite_secret`: 32 bytes or NULL.
// `session_key`: this player's FPP session key, which proves itself to the
// host now and signs InputCommits later. `attestation`: this device's
// Attestation Result, or empty (≤ `FPP_P2P_MAX_ATTESTATION`). `hello`:
// title bytes for the host (≤ `FPP_P2P_MAX_HELLO`). The first handshake
// datagram is queued; drain `fpp_p2p_joiner_poll_transmit`.
//
// # Safety
// Pointers valid as documented; `out` valid for a pointer write.
enum FppStatus fpp_p2p_joiner_new(const uint8_t *host_static_public,
                                  const uint8_t *invite_secret,
                                  const struct FppSigner *session_key,
                                  const uint8_t *attestation,
                                  size_t attestation_len,
                                  const uint8_t *hello,
                                  size_t hello_len,
                                  const uint8_t *host_addr,
                                  size_t host_addr_len,
                                  struct FppP2pJoiner **out);

// Feed one datagram received from `from`. Non-OK: it was dropped.
//
// # Safety
// `joiner` a live handle; `from` valid for `from_len`; `datagram` valid for `len`.
enum FppStatus fpp_p2p_joiner_recv(struct FppP2pJoiner *joiner,
                                   const uint8_t *from,
                                   size_t from_len,
                                   const uint8_t *datagram,
                                   size_t len);

// Queue an application datagram for the host (≤ `FPP_P2P_MAX_PAYLOAD`).
// `FPP_STATUS_P2P_STATE` until connected.
//
// # Safety
// `joiner` a live handle; `payload` valid for `len` bytes.
enum FppStatus fpp_p2p_joiner_send(struct FppP2pJoiner *joiner, const uint8_t *payload, size_t len);

// Queue a message on the reliable ordered channel (≤ `FPP_P2P_MAX_MESSAGE`).
//
// # Safety
// `joiner` a live handle; `payload` valid for `len` bytes.
enum FppStatus fpp_p2p_joiner_send_reliable(struct FppP2pJoiner *joiner,
                                            const uint8_t *payload,
                                            size_t len);

// Advance time (monotonic ms): queues an ack and due retransmissions.
// Call once per game tick.
//
// # Safety
// `joiner` a live handle.
enum FppStatus fpp_p2p_joiner_tick(struct FppP2pJoiner *joiner, uint64_t now_ms);

// Queue an empty keepalive.
//
// # Safety
// `joiner` a live handle.
enum FppStatus fpp_p2p_joiner_keepalive(struct FppP2pJoiner *joiner);

// Queue a fresh handshake if not connected yet (call on a retry timer,
// e.g. every 500 ms). No effect once connected.
//
// # Safety
// `joiner` a live handle.
enum FppStatus fpp_p2p_joiner_retry(struct FppP2pJoiner *joiner);

// Tell the host we leave (`reason`: an `fpp_types::Reason` code), then stop.
//
// # Safety
// `joiner` a live handle.
enum FppStatus fpp_p2p_joiner_close(struct FppP2pJoiner *joiner, uint16_t reason);

// Like `fpp_p2p_host_poll_transmit`.
//
// # Safety
// As for `fpp_p2p_host_poll_transmit`, with a live joiner handle.
enum FppStatus fpp_p2p_joiner_poll_transmit(struct FppP2pJoiner *joiner,
                                            uint8_t *to,
                                            size_t to_cap,
                                            size_t *to_len,
                                            uint8_t *packet,
                                            size_t cap,
                                            size_t *len);

// Like `fpp_p2p_host_poll_event`.
//
// # Safety
// As for `fpp_p2p_host_poll_event`, with a live joiner handle.
enum FppStatus fpp_p2p_joiner_poll_event(struct FppP2pJoiner *joiner,
                                         struct FppP2pEvent *event,
                                         uint8_t *data,
                                         size_t cap);

// # Safety
// `joiner` NULL or a live handle; not used afterwards.
void fpp_p2p_joiner_free(struct FppP2pJoiner *joiner);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FPP_H */
