/* fpp.h: Fair-Play Protocol v1 SDK for C/C++ games.
 *
 * GENERATED by cbindgen from crates/fpp-ffi/src/lib.rs. Do not edit; run
 * `FPP_REGEN_HEADER=1 cargo test -p fpp-ffi --test header` after changing the
 * Rust side. Spec: docs/anticheat/04-protocol.md. Plain C99, 32- and 64-bit.
 */

#ifndef FPP_H
#define FPP_H

#include <stddef.h>
#include <stdint.h>

// Result of every SDK call. Verification failures map one-to-one onto the
// rejection categories of 04-protocol.md §2.1.
typedef enum FppStatus {
  FPP_STATUS_OK = 0,
  // A required pointer was NULL.
  FPP_STATUS_NULL_POINTER = 1,
  // An argument is out of range or breaks an ordering rule.
  FPP_STATUS_INVALID_ARGUMENT = 2,
  // `*out_len` holds the required size.
  FPP_STATUS_BUFFER_TOO_SMALL = 3,
  FPP_STATUS_ENCODING = 10,
  FPP_STATUS_HEADER = 11,
  FPP_STATUS_VERSION = 12,
  FPP_STATUS_CONTEXT = 13,
  FPP_STATUS_UNKNOWN_KEY = 14,
  FPP_STATUS_ROLE = 15,
  FPP_STATUS_ALGORITHM = 16,
  FPP_STATUS_SIGNATURE = 17,
  FPP_STATUS_SCHEMA = 18,
  // A bug in the SDK (a caught panic). Please report it.
  FPP_STATUS_INTERNAL = 99,
} FppStatus;

// Accumulates a host's commitment for one match epoch (04-protocol.md §8.1).
typedef struct FppCheckpointBuilder FppCheckpointBuilder;

// Accumulates one player's input frames for one epoch (04-protocol.md §7.4).
typedef struct FppInputCommitBuilder FppInputCommitBuilder;

// An Ed25519 signing key (a player's session key or a host's instance key).
typedef struct FppSigner FppSigner;

// Fields of a verified InputCommit, plus its object digest.
typedef struct FppInputCommitInfo {
  uint8_t match_id[16];
  uint16_t slot;
  uint32_t epoch;
  uint32_t first_tick;
  uint32_t last_tick;
  uint32_t n;
  uint8_t frames_root[32];
  uint8_t prev[32];
  uint8_t digest[32];
} FppInputCommitInfo;

// Fields of a verified Checkpoint, plus its object digest.
typedef struct FppCheckpointInfo {
  uint8_t match_id[16];
  uint8_t gs_instance_id[32];
  uint8_t build_id[32];
  uint64_t policy_ver;
  uint32_t epoch;
  uint32_t first_tick;
  uint32_t last_tick;
  uint8_t prev[32];
  uint8_t inputs_root[32];
  uint32_t inputs_n;
  uint8_t events_root[32];
  uint32_t events_n;
  uint8_t state_root[32];
  uint8_t rng_root[32];
  uint32_t rng_n;
  uint8_t roster_root[32];
  uint32_t roster_n;
  uint8_t digest[32];
} FppCheckpointInfo;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// ABI version of this header. Increments on any incompatible change.
uint32_t fpp_abi_version(void);

// Static, human-readable name of a status code (never NULL).
const char *fpp_status_str(int status);

// SHA-256 of `data`.
//
// # Safety
// `data` valid for `len` bytes (or NULL with `len` 0); `out` valid for 32 bytes.
enum FppStatus fpp_sha256(const uint8_t *data, size_t len, uint8_t *out);

// Digest of a signed object (its exact bytes): the value for `prev` links and
// for InputLeaf commit references.
//
// # Safety
// `object` valid for `len` bytes; `out` valid for 32 bytes.
enum FppStatus fpp_object_digest(const uint8_t *object, size_t len, uint8_t *out);

// Generate a fresh key from the OS random number generator.
//
// # Safety
// `out` valid for a pointer write. Free the result with `fpp_signer_free`.
enum FppStatus fpp_signer_generate(struct FppSigner **out);

// Recreate a key from a 32-byte seed (deterministic; for tests and for keys
// the game persists itself).
//
// # Safety
// `seed` valid for 32 bytes; `out` valid for a pointer write.
enum FppStatus fpp_signer_from_seed(const uint8_t *seed, struct FppSigner **out);

// # Safety
// `signer` NULL or a live handle; not used afterwards.
void fpp_signer_free(struct FppSigner *signer);

// The key's 32-byte Ed25519 public key (what peers need to verify it).
//
// # Safety
// `signer` a live handle; `out` valid for 32 bytes.
enum FppStatus fpp_signer_public_key(const struct FppSigner *signer, uint8_t *out);

// SHA-256 of a public key's COSE_Key: the `gs_instance_id` of a host key.
// The first 16 bytes are the key's `kid`.
//
// # Safety
// `public_key` valid for 32 bytes; `out` valid for 32 bytes.
enum FppStatus fpp_key_digest(const uint8_t *public_key, uint8_t *out);

// Start an epoch's commitment. `match_id`: 16 bytes. `prev`: 32 bytes, the
// digest of this player's previous signed InputCommit, or NULL at epoch 0.
// Requires `first_tick <= last_tick`.
//
// # Safety
// Pointers valid as documented; `out` valid for a pointer write.
enum FppStatus fpp_input_commit_begin(const uint8_t *match_id,
                                      uint16_t slot,
                                      uint32_t epoch,
                                      uint32_t first_tick,
                                      uint32_t last_tick,
                                      const uint8_t *prev,
                                      struct FppInputCommitBuilder **out);

// Add the frame (title-defined intent bytes) sent for `tick`. Ticks must be
// strictly ascending and inside the epoch's range.
//
// # Safety
// `builder` a live handle; `payload` valid for `len` bytes.
enum FppStatus fpp_input_commit_add_frame(struct FppInputCommitBuilder *builder,
                                          uint32_t tick,
                                          const uint8_t *payload,
                                          size_t len);

// Merkle root of the frames added so far. A host builds one from the frames
// it received and compares it with the player's signed `frames_root`.
//
// # Safety
// `builder` a live handle; `out` valid for 32 bytes.
enum FppStatus fpp_input_commit_frames_root(const struct FppInputCommitBuilder *builder,
                                            uint8_t *out);

// Sign the commitment with the player's session key. Does not consume the
// builder; signing is deterministic, so a size query followed by a second
// call yields the same bytes.
//
// # Safety
// Handles live; `out` valid for `cap` bytes or NULL; `out_len` valid.
enum FppStatus fpp_input_commit_sign(const struct FppInputCommitBuilder *builder,
                                     const struct FppSigner *session_key,
                                     uint8_t *out,
                                     size_t cap,
                                     size_t *out_len);

// # Safety
// `builder` NULL or a live handle; not used afterwards.
void fpp_input_commit_free(struct FppInputCommitBuilder *builder);

// Start a checkpoint. `match_id`: 16 bytes; `build_id`: 32 bytes; `prev`: 32
// bytes (digest of the previous signed Checkpoint) or NULL at epoch 0.
//
// # Safety
// Pointers valid as documented; `out` valid for a pointer write.
enum FppStatus fpp_checkpoint_begin(const uint8_t *match_id,
                                    const uint8_t *build_id,
                                    uint64_t policy_ver,
                                    uint32_t epoch,
                                    uint32_t first_tick,
                                    uint32_t last_tick,
                                    const uint8_t *prev,
                                    struct FppCheckpointBuilder **out);

// Add one player slot's input record, in strictly ascending slot order.
// `commit_digest`: 32 bytes (`fpp_object_digest` of the player's signed
// InputCommit) or NULL if none arrived. `applied`: bitset over the epoch's
// ticks, bit i (LSB-first per byte) set when the frame for `first_tick + i`
// was applied in time; exactly `ceil(ticks / 8)` bytes.
//
// # Safety
// `builder` a live handle; pointers valid as documented.
enum FppStatus fpp_checkpoint_add_input(struct FppCheckpointBuilder *builder,
                                        uint16_t slot,
                                        const uint8_t *commit_digest,
                                        const uint8_t *applied,
                                        size_t applied_len);

// Append an authoritative event (title-defined bytes), in simulation order.
//
// # Safety
// `builder` a live handle; `data` valid for `len` bytes.
enum FppStatus fpp_checkpoint_add_event(struct FppCheckpointBuilder *builder,
                                        const uint8_t *data,
                                        size_t len);

// Append a VRF proof for an outcome roll made this epoch.
//
// # Safety
// `builder` a live handle; `data` valid for `len` bytes.
enum FppStatus fpp_checkpoint_add_rng(struct FppCheckpointBuilder *builder,
                                      const uint8_t *data,
                                      size_t len);

// Append a roster entry (slot, admission token id, device id) for an admitted player.
//
// # Safety
// `builder` a live handle; `data` valid for `len` bytes.
enum FppStatus fpp_checkpoint_add_roster(struct FppCheckpointBuilder *builder,
                                         const uint8_t *data,
                                         size_t len);

// Set the digest of the canonical audit-projection state at `last_tick`
// (32 bytes). Defaults to all zeros for titles without an audit projection yet.
//
// # Safety
// `builder` a live handle; `root` valid for 32 bytes.
enum FppStatus fpp_checkpoint_set_state_root(struct FppCheckpointBuilder *builder,
                                             const uint8_t *root);

// Sign the checkpoint with the host's instance key. `gs_instance_id` is
// derived from that key. Does not consume the builder.
//
// # Safety
// Handles live; `out` valid for `cap` bytes or NULL; `out_len` valid.
enum FppStatus fpp_checkpoint_sign(const struct FppCheckpointBuilder *builder,
                                   const struct FppSigner *instance_key,
                                   uint8_t *out,
                                   size_t cap,
                                   size_t *out_len);

// # Safety
// `builder` NULL or a live handle; not used afterwards.
void fpp_checkpoint_free(struct FppCheckpointBuilder *builder);

// Verify a signed InputCommit against a player's 32-byte session public key.
// On success fills `*info` if it is not NULL.
//
// # Safety
// `object` valid for `len` bytes; `session_public_key` valid for 32 bytes;
// `info` NULL or valid for a write.
enum FppStatus fpp_verify_input_commit(const uint8_t *object,
                                       size_t len,
                                       const uint8_t *session_public_key,
                                       struct FppInputCommitInfo *info);

// Verify a signed Checkpoint against a host's 32-byte instance public key,
// and check that `gs_instance_id` names that key. On success fills `*info`
// if it is not NULL.
//
// # Safety
// `object` valid for `len` bytes; `instance_public_key` valid for 32 bytes;
// `info` NULL or valid for a write.
enum FppStatus fpp_verify_checkpoint(const uint8_t *object,
                                     size_t len,
                                     const uint8_t *instance_public_key,
                                     struct FppCheckpointInfo *info);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FPP_H */
