[package]
name = "tools"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish.workspace = true

[[bin]]
name = "gen_keys"
path = "src/gen_keys.rs"

[[bin]]
name = "smoke"
path = "src/smoke.rs"

[[bin]]
name = "play"
path = "src/play.rs"

[[bin]]
name = "mint_ar"
path = "src/mint_ar.rs"

[dependencies]
clap = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { workspace = true }
ctrlc = { workspace = true }
anyhow = { workspace = true }
common = { path = "../common" }
fpp-crypto = { path = "../fpp-crypto" }
fpp-tokens = { path = "../fpp-tokens" }
fpp-types = { path = "../fpp-types" }