//! A session key that lives in the TPM (roadmap P3; 04 §3 ES256): a P-256
//! signing key the TPM made and will not let out, certified by the
//! Attestation Key (`TPM2_Certify`, a `TPMS_ATTEST` of type
//! `TPM_ST_ATTEST_CERTIFY`, Part 2 10.12.3).
//!
//! The certification names the key (its Name, the digest of its public
//! area); the public area says how the key was made. With the AK tied to a
//! genuine TPM by credential activation, a valid certification proves the
//! session key cannot be copied off the machine. Freshness comes from the
//! quote (whose nonce names this session key and the Verifier's challenge)
//! and from the session key's own proof of possession.

use crate::marshal::Reader;
use crate::public::{attr, KeyParams, Public};
use crate::quote::{verify_ak_signature, TPM_GENERATED};
use crate::{alg, TpmError};

pub const ST_ATTEST_CERTIFY: u16 = 0x8017;

/// A parsed `TPMS_ATTEST` certification.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Certification {
    pub extra_data: Vec<u8>,
    /// The certified object's Name and qualified Name.
    pub name: Vec<u8>,
    pub qualified_name: Vec<u8>,
}

impl Certification {
    pub fn parse(bytes: &[u8]) -> Result<Self, TpmError> {
        let mut r = Reader::new(bytes, "TPMS_ATTEST");
        if r.u32()? != TPM_GENERATED {
            return Err(TpmError::Policy("not generated by a TPM (magic)"));
        }
        if r.u16()? != ST_ATTEST_CERTIFY {
            return Err(TpmError::Policy("not a certification"));
        }
        let _qualified_signer = r.tpm2b()?;
        let extra_data = r.tpm2b()?.to_vec();
        // clockInfo, firmwareVersion
        r.bytes(8 + 4 + 4 + 1 + 8)?;
        let name = r.tpm2b()?.to_vec();
        let qualified_name = r.tpm2b()?.to_vec();
        r.end()?;
        Ok(Certification {
            extra_data,
            name,
            qualified_name,
        })
    }
}

/// Check that the AK certified `session` (a `TPM2B_PUBLIC`), and that it is
/// a P-256 signing key made in the TPM, fixed to it, that signs any digest
/// (not restricted): an FPP session key. Returns it as an uncompressed SEC1
/// point (`0x04 ‖ x ‖ y`, `SessionKey::to_bytes`).
pub fn verify_session_key(
    ak: &Public,
    attest: &[u8],
    signature: &[u8],
    session: &[u8],
) -> Result<Vec<u8>, TpmError> {
    verify_ak_signature(ak, attest, signature)?;
    let certification = Certification::parse(attest)?;
    let key = Public::from_tpm2b(session)?;
    if certification.name != key.name()? {
        return Err(TpmError::Policy("the certification names another key"));
    }
    let required =
        attr::FIXED_TPM | attr::FIXED_PARENT | attr::SENSITIVE_DATA_ORIGIN | attr::SIGN_ENCRYPT;
    if !key.has(required) || key.has(attr::DECRYPT) || key.has(attr::RESTRICTED) {
        return Err(TpmError::Policy(
            "not an unrestricted signing key made in and fixed to the TPM",
        ));
    }
    match &key.params {
        KeyParams::Ecc {
            scheme,
            curve: alg::NIST_P256,
            x,
            y,
        } if matches!(*scheme, (alg::NULL, None) | (alg::ECDSA, Some(alg::SHA256)))
            && x.len() == 32
            && y.len() == 32 =>
        {
            let mut point = vec![4u8];
            point.extend_from_slice(x);
            point.extend_from_slice(y);
            Ok(point)
        }
        _ => Err(TpmError::Unsupported(
            "session key other than ECDSA P-256/SHA-256",
        )),
    }
}
