//! Quotes: `TPMS_ATTEST` of type `TPM_ST_ATTEST_QUOTE` (TPM 2.0 Part 2,
//! 10.12.8), signed by an Attestation Key as a `TPMT_SIGNATURE` (11.3.4).
//!
//! What a valid quote proves: a key that never leaves a TPM (checked by
//! [`Public::check_attestation_key`], and tied to a genuine TPM's EK by
//! credential activation, [`crate::credential`]) signed, over the Verifier's
//! nonce, the digest of the listed PCRs. The PCR values themselves travel
//! beside the quote; they count only because their digest matches.

use std::collections::BTreeMap;

use aws_lc_rs::signature::{self, RsaPublicKeyComponents, UnparsedPublicKey};

use crate::marshal::Reader;
use crate::public::{hash, hash_len, KeyParams, Public};
use crate::{alg, TpmError};

/// `TPM_GENERATED_VALUE`: only the TPM puts this at the head of a structure
/// it signs with a restricted key, and a restricted key signs no digest the
/// TPM did not compute from a structure it generated.
pub const TPM_GENERATED: u32 = 0xff54_4347;
pub const ST_ATTEST_QUOTE: u16 = 0x8018;

/// PCR values: index to the bank's digest.
pub type Pcrs = BTreeMap<u8, Vec<u8>>;

/// A parsed `TPMS_ATTEST` quote.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Attest {
    pub qualified_signer: Vec<u8>,
    /// The Verifier's nonce (`qualifyingData`).
    pub extra_data: Vec<u8>,
    pub clock: u64,
    pub reset_count: u32,
    pub restart_count: u32,
    pub safe: bool,
    pub firmware_version: u64,
    /// (hash algorithm, selected PCR indices), in the quote's order.
    pub selection: Vec<(u16, Vec<u8>)>,
    pub pcr_digest: Vec<u8>,
}

impl Attest {
    pub fn parse(bytes: &[u8]) -> Result<Self, TpmError> {
        let mut r = Reader::new(bytes, "TPMS_ATTEST");
        if r.u32()? != TPM_GENERATED {
            return Err(TpmError::Policy("not generated by a TPM (magic)"));
        }
        if r.u16()? != ST_ATTEST_QUOTE {
            return Err(TpmError::Policy("not a quote"));
        }
        let qualified_signer = r.tpm2b()?.to_vec();
        let extra_data = r.tpm2b()?.to_vec();
        let clock = r.u64()?;
        let reset_count = r.u32()?;
        let restart_count = r.u32()?;
        let safe = r.u8()? != 0;
        let firmware_version = r.u64()?;
        let count = r.u32()?;
        if count > 16 {
            return Err(TpmError::Malformed("PCR selection count"));
        }
        let mut selection = Vec::new();
        for _ in 0..count {
            let hash_alg = r.u16()?;
            let size = r.u8()? as usize;
            if size > 4 {
                return Err(TpmError::Malformed("PCR selection size"));
            }
            let bitmap = r.bytes(size)?;
            let mut pcrs = Vec::new();
            for (byte, bits) in bitmap.iter().enumerate() {
                for bit in 0..8 {
                    if bits & (1 << bit) != 0 {
                        pcrs.push((byte * 8 + bit) as u8);
                    }
                }
            }
            selection.push((hash_alg, pcrs));
        }
        let pcr_digest = r.tpm2b()?.to_vec();
        r.end()?;
        Ok(Attest {
            qualified_signer,
            extra_data,
            clock,
            reset_count,
            restart_count,
            safe,
            firmware_version,
            selection,
            pcr_digest,
        })
    }
}

/// A `TPMT_SIGNATURE`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Signature {
    Rsa {
        scheme: u16,
        hash: u16,
        sig: Vec<u8>,
    },
    Ecdsa {
        hash: u16,
        r: Vec<u8>,
        s: Vec<u8>,
    },
}

impl Signature {
    pub fn parse(bytes: &[u8]) -> Result<Self, TpmError> {
        let mut r = Reader::new(bytes, "TPMT_SIGNATURE");
        let scheme = r.u16()?;
        let sig = match scheme {
            alg::RSASSA | alg::RSAPSS => Signature::Rsa {
                scheme,
                hash: r.u16()?,
                sig: r.tpm2b()?.to_vec(),
            },
            alg::ECDSA => Signature::Ecdsa {
                hash: r.u16()?,
                r: r.tpm2b()?.to_vec(),
                s: r.tpm2b()?.to_vec(),
            },
            _ => return Err(TpmError::Unsupported("signature scheme")),
        };
        r.end()?;
        Ok(sig)
    }

    fn scheme(&self) -> (u16, u16) {
        match self {
            Signature::Rsa { scheme, hash, .. } => (*scheme, *hash),
            Signature::Ecdsa { hash, .. } => (alg::ECDSA, *hash),
        }
    }
}

fn left_pad(v: &[u8], n: usize) -> Result<Vec<u8>, TpmError> {
    let v = &v[v.iter().take_while(|b| **b == 0).count().min(v.len())..];
    if v.len() > n {
        return Err(TpmError::Malformed("ECC value size"));
    }
    let mut out = vec![0u8; n - v.len()];
    out.extend_from_slice(v);
    Ok(out)
}

/// Verify `sig` over `message` with a TPM public key.
pub fn verify_signature(key: &Public, message: &[u8], sig: &Signature) -> Result<(), TpmError> {
    let bad = || TpmError::BadSignature;
    match (&key.params, sig) {
        (
            KeyParams::Rsa {
                modulus, exponent, ..
            },
            Signature::Rsa { scheme, hash, sig },
        ) => {
            let alg: &'static signature::RsaParameters = match (*scheme, *hash) {
                (alg::RSASSA, alg::SHA256) => &signature::RSA_PKCS1_2048_8192_SHA256,
                (alg::RSASSA, alg::SHA384) => &signature::RSA_PKCS1_2048_8192_SHA384,
                (alg::RSAPSS, alg::SHA256) => &signature::RSA_PSS_2048_8192_SHA256,
                (alg::RSAPSS, alg::SHA384) => &signature::RSA_PSS_2048_8192_SHA384,
                _ => return Err(TpmError::Unsupported("RSA signature hash")),
            };
            let e = exponent.to_be_bytes();
            let e = &e[e.iter().take_while(|b| **b == 0).count()..];
            RsaPublicKeyComponents {
                n: modulus.as_slice(),
                e,
            }
            .verify(alg, message, sig)
            .map_err(|_| bad())
        }
        (KeyParams::Ecc { curve, x, y, .. }, Signature::Ecdsa { hash, r, s }) => {
            let (alg, n): (&'static signature::EcdsaVerificationAlgorithm, usize) =
                match (*curve, *hash) {
                    (alg::NIST_P256, alg::SHA256) => (&signature::ECDSA_P256_SHA256_FIXED, 32),
                    (alg::NIST_P384, alg::SHA384) => (&signature::ECDSA_P384_SHA384_FIXED, 48),
                    _ => return Err(TpmError::Unsupported("ECDSA curve and hash")),
                };
            let mut point = vec![4u8];
            point.extend(left_pad(x, n)?);
            point.extend(left_pad(y, n)?);
            let mut rs = left_pad(r, n)?;
            rs.extend(left_pad(s, n)?);
            UnparsedPublicKey::new(alg, &point)
                .verify(message, &rs)
                .map_err(|_| bad())
        }
        _ => Err(TpmError::BadSignature),
    }
}

/// The AK's signature over a `TPMS_ATTEST` it made (a quote, a
/// certification): the AK's attributes, its scheme, the signature.
pub fn verify_ak_signature(
    ak: &Public,
    attest_bytes: &[u8],
    signature_bytes: &[u8],
) -> Result<Signature, TpmError> {
    ak.check_attestation_key()?;
    let sig = Signature::parse(signature_bytes)?;
    // (a key made for one scheme signs with no other)
    let key_scheme = match &ak.params {
        KeyParams::Rsa { scheme, .. } | KeyParams::Ecc { scheme, .. } => *scheme,
    };
    if key_scheme.0 != alg::NULL
        && (key_scheme.0, key_scheme.1) != (sig.scheme().0, Some(sig.scheme().1))
    {
        return Err(TpmError::Policy("signature scheme differs from the key's"));
    }
    verify_signature(ak, attest_bytes, &sig)?;
    Ok(sig)
}

/// What a verified quote established.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Quote {
    pub attest: Attest,
    /// The quoted bank's algorithm and its PCRs' values (checked against
    /// the signed digest).
    pub hash_alg: u16,
    pub pcrs: Pcrs,
}

/// Verify a quote: the Attestation Key's attributes, its signature over
/// the `TPMS_ATTEST`, the nonce, and the PCR values against the signed
/// digest. One PCR bank per quote (the SHA-256 one in practice).
///
/// The caller must also know the AK belongs to a genuine TPM: an AK it
/// enrolled by credential activation against a verified EK certificate
/// ([`crate::credential`], [`crate::ek`]).
pub fn verify_quote(
    ak: &Public,
    attest_bytes: &[u8],
    signature_bytes: &[u8],
    nonce: &[u8],
    pcrs: &Pcrs,
) -> Result<Quote, TpmError> {
    let sig = verify_ak_signature(ak, attest_bytes, signature_bytes)?;
    let attest = Attest::parse(attest_bytes)?;
    if attest.extra_data != nonce {
        return Err(TpmError::NonceMismatch);
    }
    let [(hash_alg, selected)] = attest.selection.as_slice() else {
        return Err(TpmError::Unsupported("quotes of more than one PCR bank"));
    };
    let size = hash_len(*hash_alg)?;
    let mut concatenated = Vec::new();
    let mut quoted = Pcrs::new();
    for index in selected {
        let value = pcrs
            .get(index)
            .ok_or(TpmError::Policy("a quoted PCR's value is missing"))?;
        if value.len() != size {
            return Err(TpmError::Malformed("PCR value size"));
        }
        concatenated.extend_from_slice(value);
        quoted.insert(*index, value.clone());
    }
    if pcrs.len() != quoted.len() {
        return Err(TpmError::Policy(
            "PCR values given that the quote does not cover",
        ));
    }
    // (the digest is the signing scheme's hash of the values, whatever
    // the bank: Part 3, TPM2_Quote)
    if hash(sig.scheme().1, &concatenated)? != attest.pcr_digest {
        return Err(TpmError::PcrDigestMismatch);
    }
    Ok(Quote {
        hash_alg: *hash_alg,
        pcrs: quoted,
        attest,
    })
}
