[package]
name = "common"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow           = { workspace = true }

tokio            = { workspace = true }
quinn            = { workspace = true }
rustls           = { workspace = true }
rcgen            = { workspace = true }

serde            = { workspace = true }
serde-big-array  = { workspace = true }
bincode          = { workspace = true }

ed25519-dalek    = { workspace = true }
sha2             = { workspace = true }
rand             = { workspace = true }
hex              = { workspace = true }
serde_json       = { workspace = true }

fpp-crypto       = { path = "../fpp-crypto" }
fpp-types        = { path = "../fpp-types" }


[features]
default = []
